//================================================ SERVER SETUP ================================================//

const express = require("express");
const app = express();
const db = require("./db.js");
const s3 = require("./s3.js");
const moment = require("moment");

app.use(express.static("./public"));
app.use(express.json());

// app.use((req, res, next) => {
//     console.log(req.method);
//     next();
// });

//================================================ MULTER SETUP ================================================//

const multer = require("multer");
const uidSafe = require("uid-safe");
const path = require("path");

const diskStorage = multer.diskStorage({
    // put files in the uploads directory
    destination: function (req, file, callback) {
        callback(null, __dirname + "/uploads");
    },
    // as the file name, use the unique id generated by the call to uidSafe with the extension of the original file name appended to it
    filename: function (req, file, callback) {
        uidSafe(24).then(function (uid) {
            callback(null, uid + path.extname(file.originalname));
        });
    },
});

const uploader = multer({
    storage: diskStorage,
    limits: {
        fileSize: 2097152,
    },
});

//================================================ ROUTES ================================================//

// The call to single indicates that we are   ↓↓↓↓   only expecting one single file to be uploaded
app.post("/upload", uploader.single("file"), s3.upload, function (req, res) {
    if (req.file) {
        // once we're successfully uploaded to the cloud, we want to
        // add a new image to the database!
        const { title, desc, username, tags } = req.body;
        const url = `https://s3.amazonaws.com/spicedling/` + req.file.filename;

        const tagsArr = tags.split(",");

        db.addImage(url, username, title, desc)
            .then((image) => {
                image.rows[0].publDate = moment(
                    image.rows[0].created_at
                ).fromNow();

                return image.rows[0].id;
            })
            .then((imageId) =>
                Promise.all(tagsArr.map((tag) => db.addTag(imageId, tag)))
            )
            .then((tags) => tags[0].rows[0].id)
            .then((imageId) => db.getImageById(imageId))
            .then((image) => {
                // we want to send back the newly uploaded image object to our client side
                res.json(image.rows[0]);
            })
            .catch((err) => {
                console.log("err in addImage on POST /upload: ", err);
                return res.sendStatus(500);
            });
    } else {
        // boo hoo
        res.json({
            success: false,
        });
    }
});

app.get("/images.json", (req, res) => {
    db.getImages()
        .then((images) => {
            // format the date property to the "1 day ago" format via moment
            // and store it in the publDate property
            images.rows.forEach(
                (row) => (row.publDate = moment(row.date).fromNow())
            );
            res.json(images);
        })
        .catch((err) => {
            console.log("err in getImages() on GET /images.json", err);
            res.sendStatus(500);
        });
});

app.get("/selected-image/:id", (req, res) => {
    const { id } = req.params;

    Promise.all([db.getImageById(id), db.getTagsById(id)])
        .then((results) => {
            const image = results[0];
            const tags = results[1];

            if (image.rows.length !== 0) {
                image.rows[0].publDate = moment(image.rows[0].date).fromNow();
            }

            // we want to send back the newly uploaded image object to our client side
            res.json([image, tags]);
        })
        .catch((err) => {
            console.log("err in getImageById() on GET /selected-image/id", err);
            res.sendStatus(500);
        });
});

app.get("/more-images/:smallestImageId", (req, res) => {
    const { smallestImageId } = req.params;

    db.getImages(smallestImageId)
        .then((images) => {
            images.rows.forEach(
                (row) => (row.publDate = moment(row.date).fromNow())
            );
            res.json(images);
        })
        .catch((err) => {
            console.log("err in getImages() on GET /more-images/", err);
            res.sendStatus(500);
        });
});

app.get("/filter-images/:tag", (req, res) => {
    const { tag } = req.params;
    db.getImagesByTag(tag)
        .then((images) => {
            images.rows.forEach(
                (row) => (row.publDate = moment(row.date).fromNow())
            );
            res.json(images);
        })
        .catch((err) => {
            console.log("err in getImagesByTag() on GET /filter-images/", err);
            res.sendStatus(500);
        });
});

app.get("/comments/:imageId", (req, res) => {
    const { imageId } = req.params;
    db.getComments(imageId)
        .then((comments) => {
            // format the date property to the "1 day ago" format via moment
            // and store it in the publDate property
            comments.rows.forEach(
                (row) => (row.publDate = moment(row.date).fromNow())
            );
            res.json(comments);
        })
        .catch((err) => {
            console.log("err in getComments() on GET /comments.json", err);
            res.sendStatus(500);
        });
});

app.post("/add-comment", (req, res) => {
    const { imageId, username, comment } = req.body;

    db.addComment(imageId, username, comment)
        .then((comment) => {
            res.json(comment.rows[0]);
        })
        .catch((err) => {
            console.log("err in addComment on POST /add-comment", err);
            res.sendStatus(500);
        });
});

app.get("*", (req, res) => {
    res.sendFile(`${__dirname}/index.html`);
});

//================================================ PORT ================================================//

app.listen(8080, () => console.log(`I'm listening.`));
